CREAR LISTAS, SERIES DICCIONARIOS Y DATAFRAME, VIDEO 3

In [1]:
import pandas as pd

In [ ]:
# Listas y Series en pandas, son estructuras unidimensionales, solo una columna
#crear una lista
numeros = [3, 4, 5, 6, 7]
# creamos la serie con la lista numeros
serie = pd.Series(numeros)
# se imprime
serie, type(serie)

(0    3
 1    4
 2    5
 3    6
 4    7
 dtype: int64,
 pandas.Series)

In [5]:
# Diccionario de datos, contiene claves y valores, como un json
data = {
    "Nombre":["julio", "camilo", "ramiro", "camila"],
    "Edad":[22, 35, 67, 12],
    "Color":["rojo", "verde", "amarillo", "negro"]
}
data, type(data)

({'Nombre': ['julio', 'camilo', 'ramiro', 'camila'],
  'Edad': [22, 35, 67, 12],
  'Color': ['rojo', 'verde', 'amarillo', 'negro']},
 dict)

In [ ]:
# Crear un data Frame, estructura bidimensional, como una tabla, con multiples columnas 
# para el ejemplo se construye el dataFrame a partir del diccionario creado anteriormente, cada clave sera una
# columna y su valor sera un elemento de esa columna

df = pd.DataFrame(data=data) 
df

   Nombre  Edad     Color
0   julio    22      rojo
1  camilo    35     verde
2  ramiro    67  amarillo
3  camila    12     negro

IMPORTAR Y EXPORTAR ARCHIVOS CON PANDAS, VIDEO 4

In [ ]:
# Exportar un dataFrame df en formato .csv, el archivo se crea en la carpeta del proyecto por defecto

df.to_csv('ejemploExportar')

# Para exportar cambiando el delimitador se usa el argumento sep='', punto y coma
df.to_csv('archivo.csv', sep=';')

# Para usar delimitador de archivos TXT:
df.to_csv('archivo.txt', sep='\t', index=False)

# Para exportar en otra ubicación usamos la siguiente instrucción, la r es para que ignore las "\"

# df.to_csv(r'C:\Users\TuUsuario\Desktop\ejemploExportar.csv', index=False)

In [ ]:
# Para importar el archivo, se crea una variable, para qiutar la columna de index que aparece por \
# defecto usar index_col=0

import_df = pd.read_csv('ejemploExportar', index_col=0)
import_df

# Para importar cambiando el delimitador:
pd.read_csv('archivo.csv', sep=';')

# Para importar archivos con delimitador TXT
pd.read_csv('archivo.txt', sep='\t')

# Para importar desde otras ubicaciones usar la misma lógica:
# import_df = pd.read_csv(r'C:\Tu\Carpeta\Externa\ejemploExportar.csv', index_col=0)
# import_df

   Nombre  Edad     Color
0   julio    22      rojo
1  camilo    35     verde
2  ramiro    67  amarillo
3  camila    12     negro

MANIPULACION DE DATOS CON PANDAS, VIDEO 5

In [22]:
# Seleccionar una columna del df

nombres = df["Nombre"]
print(nombres, type(nombres))

0     julio
1    camilo
2    ramiro
3    camila
Name: Nombre, dtype: str <class 'pandas.Series'>

In [24]:
# Para seleccionar mas de una columna

df[["Nombre","Edad"]]

   Nombre  Edad
0   julio    22
1  camilo    35
2  ramiro    67
3  camila    12

In [26]:
# Filtrar por el loc del df
fila = df.loc[0]
fila

Nombre    julio
Edad         22
Color      rojo
Name: 0, dtype: object

In [27]:
# Filtra por una condición especifica

df[df["Edad"] > 50]

   Nombre  Edad     Color
2  ramiro    67  amarillo

In [34]:
# Filtrar por dos o mas series(campos, columnas)
# Con este parametro filtramos "Inicia con" para el caso co "A"

filtro = (df["Edad"] > 10) & (df["Nombre"].str.startswith("c"))
df[filtro]

   Nombre  Edad  Color
1  camilo    35  verde
3  camila    12  negro

In [36]:
# Otra forma de filtrar es con la instrucción query

df.query("Edad > 30")

   Nombre  Edad     Color
1  camilo    35     verde
2  ramiro    67  amarillo

TRATAMIENTO DE DATOS CON PANDS y NUMPY VIDEO 6

In [3]:
# Importar numpy
import numpy as np

In [ ]:
# Crear un df con valores null en campos de texto y campos numericos,
# estos valores deben ser tratados antes de aplicar cualquier tecnica de Machine Learning (missing value o imputación de datos)

data = {
    "Nombre":["julio", "camilo", "ramiro", "camila"],
    "Edad":[22, np.nan, 67, 12],
    "Color":["rojo", "verde", None, "negro"]
}
df = pd.DataFrame(data)
df

   Nombre  Edad  Color
0   julio  22.0   rojo
1  camilo   NaN  verde
2  ramiro  67.0    NaN
3  camila  12.0  negro

Los missing values (valores faltantes o NA's) son datos ausentes, nulos o no registrados en un conjunto de información (dataset), comunes en encuestas o errores de registro. La imputación de datos es el proceso de reemplazar estos huecos por valores simulados o estimados (como la media o mediana) para no perder información valiosa ni sesgar el análisis estadístico. 

Aspectos clave:
¿Por qué ocurren? Pueden ser errores de transcripción, encuestados que no responden, o información no aplicable.
Tipos de faltantes:
MCAR (Completamente al azar): La falta de datos no tiene relación con otras variables.
MAR (Al azar): La falta depende de otra variable observada.
MNAR (No al azar): La falta depende del valor faltante en sí (ej. personas con altos ingresos no los reportan).

Métodos de Imputación:
Imputación Simple: Reemplazar por la media/mediana (datos numéricos) o moda (datos categóricos).
Imputación Avanzada: Uso de algoritmos de Machine Learning (como K-NN o regresión) para predecir el valor faltante.
Riesgos: Una mala imputación puede introducir sesgos y relaciones falsas en los datos. 

La imputación es fundamental para algoritmos de Machine Learning que no permiten valores nulos, permitiendo mantener el tamaño de la muestra.

In [ ]:
## Rellenar los valores faltantes en el df anterior, con el promedio
df_fill = df.fillna(
    {
        "Edad": df["Edad"].mean(),
        "Color" : "Desconocido"
    }
)

df_fill

   Nombre       Edad        Color
0   julio  22.000000         rojo
1  camilo  33.666667        verde
2  ramiro  67.000000  Desconocido
3  camila  12.000000        negro

In [7]:
# Si en lugar de reemplazar los valores nulos queremos eliminarlos

df_sin_na = df.dropna()
df_sin_na

   Nombre  Edad  Color
0   julio  22.0   rojo
3  camila  12.0  negro